#
###################################
# Site wide configuration
####################################
#
title: Quentin Goehrig
email: quentin.360@hotmail.com
description: A website and blog for my .
url: https://renyuanz.github.io/leonids # the base hostname & protocol for your site
keywords: ["Programming", "Java", "C#", "JavaScript"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Quentin Goehrig
  avatar: take34.jpg
  job: "Developer & Designer"
  bio: "A fullstack developer who loves to build and design awesome things. Student at UW-L, working for Trane in La Crosse, WI."
  email: quentin.360@hotmail.com
  disqus-shortname: qgoehrig
  twitter:
  facebook: #username
  #google:
    #plus: #username
    #analytics: UA-62251910-2
    #verify:
    #ad-client:
    #ad-slot:
  bing-verify:
  spotify: kwentin360
  github: qgoehrig #username
  stackoverflow: 5726006/qgoehrig
  linkedin: quentin-goehrig
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
